spring:
  batch:
    job:
      enabled: true  # true : ?????? ?? ? ??? Job? ?? / false ? ??
      name: ${job.name:NONE} # ?? JOB? ?????? Default? none

    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: dbtjd1598
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      schema-locations: classpath:initsql/schema.sql
      data-locations: classpath:initsql/data.sql
      mode: always

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.sql : DEBUG
    org.hibernate.type : trace
